spring.application.name=TestGemini
spring.ai.chat.client.enabled=true

# Using Gemini Developer API (API Key)
spring.ai.google.genai.api-key=<API KEY>
spring.ai.google.genai.chat.options.model=gemini-2.0-flash

spring.ai.google.genai.chat.options.temperature=0.5


logging.level.org.springframework.web.client=debug
logging.level.org.springframework.ai.chat.client.advisor=DEBUG 
logging.level.com.gemini.TestGemini.controller=debug

springdoc.show-actuator=true
springdoc.swagger-ui.csrf.enabled: false 
springdoc.swagger-ui.path= /swagger-ui-demoGemini.html

